interface console {
    function log(address p0, address p1, string memory p2) external view;
    function log(bool p0, uint256 p1, uint256 p2, address p3) external view;
    function log(address p0, address p1, address p2) external view;
    function log(uint256 p0, address p1, address p2, string memory p3) external view;
    function log(string memory p0, address p1, bool p2, string memory p3) external view;
    function log(uint256 p0, bool p1, address p2, uint256 p3) external view;
    function log(bool p0, address p1, bool p2, uint256 p3) external view;
    function log(bool p0, uint256 p1, address p2) external view;
    function log(uint256 p0, address p1, address p2, bool p3) external view;
    function log(address p0, bool p1, uint256 p2, string memory p3) external view;
    function log(bool p0, bool p1, uint256 p2, uint256 p3) external view;
    function log(bool p0, address p1, address p2, uint256 p3) external view;
    function log(uint256 p0, address p1, uint256 p2, uint256 p3) external view;
    function log(string memory p0, address p1, uint256 p2) external view;
    function log(address p0, string memory p1, address p2, address p3) external view;
    function log(address p0, string memory p1, address p2, bool p3) external view;
    function log(address p0, address p1, address p2, bool p3) external view;
    function log(address p0, string memory p1, uint256 p2, bool p3) external view;
    function log(address p0, uint256 p1, address p2, uint256 p3) external view;
    function log(string memory p0, string memory p1, uint256 p2, address p3) external view;
    function log(bool p0, bool p1, address p2) external view;
    function log(bool p0, string memory p1, uint256 p2) external view;
    function log(bool p0, string memory p1, address p2, string memory p3) external view;
    function log(bool p0, bool p1, uint256 p2) external view;
    function log(bool p0, address p1, uint256 p2, address p3) external view;
    function log(bool p0, uint256 p1, address p2, uint256 p3) external view;
    function log(bool p0, string memory p1, uint256 p2, address p3) external view;
    function log(address p0, string memory p1, string memory p2, uint256 p3) external view;
    function log(uint256 p0, address p1, uint256 p2, address p3) external view;
    function log(uint256 p0, uint256 p1, address p2, bool p3) external view;
    function log(bool p0, string memory p1, bool p2, uint256 p3) external view;
    function log(bool p0, string memory p1, string memory p2, string memory p3) external view;
    function log(address p0, address p1, uint256 p2) external view;
    function log(bool p0, address p1, bool p2) external view;
    function log(uint256 p0, uint256 p1, uint256 p2, uint256 p3) external view;
    function log(address p0, bool p1, string memory p2, address p3) external view;
    function log(bool p0, string memory p1, uint256 p2, string memory p3) external view;
    function log(bool p0, uint256 p1, address p2, string memory p3) external view;
    function log(bool p0, address p1, bool p2, address p3) external view;
    function log(string memory p0, uint256 p1, address p2) external view;
    function log(uint256 p0, bool p1) external view;
    function log(bool p0, address p1, address p2, address p3) external view;
    function log(address p0, uint256 p1, address p2, string memory p3) external view;
    function log(address p0, string memory p1, uint256 p2, uint256 p3) external view;
    function log(bool p0, string memory p1, string memory p2, bool p3) external view;
    function log(uint256 p0, bool p1, uint256 p2) external view;
    function log(address p0, string memory p1, bool p2, address p3) external view;
    function log(uint256 p0, bool p1, bool p2) external view;
    function log(address p0, uint256 p1, uint256 p2, address p3) external view;
    function log(address p0, bool p1, string memory p2) external view;
    function log(uint256 p0, string memory p1, string memory p2, string memory p3) external view;
    function log(address p0, address p1, string memory p2, string memory p3) external view;
    function log(string memory p0, address p1, bool p2, address p3) external view;
    function log(address p0, uint256 p1, bool p2, uint256 p3) external view;
    function log(string memory p0, address p1, string memory p2, string memory p3) external view;
    function log(uint256 p0, address p1, address p2, address p3) external view;
    function log(string memory p0, bool p1, string memory p2, uint256 p3) external view;
    function log(bool p0, bool p1, string memory p2) external view;
    function log(bool p0, uint256 p1, address p2, address p3) external view;
    function log(uint256 p0, uint256 p1, string memory p2, string memory p3) external view;
    function log(bool p0, string memory p1, uint256 p2, uint256 p3) external view;
    function log(bool p0, bool p1) external view;
    function log(bool p0, bool p1, bool p2, string memory p3) external view;
    function log(bool p0, string memory p1, address p2, address p3) external view;
    function log(string memory p0, string memory p1, string memory p2, bool p3) external view;
    function log(uint256 p0, bool p1, string memory p2, uint256 p3) external view;
    function log(address p0) external view;
    function log(address p0, address p1, bool p2, bool p3) external view;
    function log(string memory p0, string memory p1, string memory p2) external view;
    function log(string memory p0, bool p1, address p2, string memory p3) external view;
    function log(address p0, bool p1, address p2, string memory p3) external view;
    function log(string memory p0, address p1) external view;
    function log(bool p0) external view;
    function log(string memory p0, bool p1, address p2, address p3) external view;
    function log(address p0, uint256 p1, uint256 p2, uint256 p3) external view;
    function log(uint256 p0, bool p1, address p2) external view;
    function log(string memory p0, uint256 p1, bool p2, bool p3) external view;
    function log(address p0, string memory p1, string memory p2, bool p3) external view;
    function log(bool p0, uint256 p1, uint256 p2) external view;
    function log(bool p0, uint256 p1, uint256 p2, uint256 p3) external view;
    function log(uint256 p0, string memory p1, uint256 p2) external view;
    function log(address p0, bool p1, uint256 p2, uint256 p3) external view;
    function log(address p0, address p1, bool p2, uint256 p3) external view;
    function log(bool p0, uint256 p1) external view;
    function log(uint256 p0, string memory p1, uint256 p2, address p3) external view;
    function log(bool p0, bool p1, bool p2, bool p3) external view;
    function log(address p0, uint256 p1, bool p2, bool p3) external view;
    function log(uint256 p0, address p1, string memory p2, string memory p3) external view;
    function log(string memory p0, address p1, bool p2, uint256 p3) external view;
    function log(string memory p0, bool p1, string memory p2, bool p3) external view;
    function log(string memory p0, string memory p1, bool p2, bool p3) external view;
    function log(string memory p0) external view;
    function log(uint256 p0, uint256 p1, string memory p2, address p3) external view;
    function log(string memory p0, string memory p1, address p2, address p3) external view;
    function log(address p0, string memory p1, uint256 p2, string memory p3) external view;
    function log(uint256 p0, bool p1, address p2, bool p3) external view;
    function log(address p0, string memory p1, address p2, uint256 p3) external view;
    function log(bool p0, address p1, address p2, bool p3) external view;
    function log(uint256 p0, address p1, string memory p2, uint256 p3) external view;
    function log(address p0, bool p1, string memory p2, string memory p3) external view;
    function log(uint256 p0, uint256 p1, bool p2) external view;
    function log(address p0, uint256 p1, address p2, address p3) external view;
    function log(bool p0, string memory p1, bool p2, string memory p3) external view;
    function log(address p0, uint256 p1, uint256 p2, string memory p3) external view;
    function log(bool p0, address p1, bool p2, string memory p3) external view;
    function log(string memory p0, string memory p1) external view;
    function log(bool p0, bool p1, address p2, uint256 p3) external view;
    function log(uint256 p0, string memory p1, bool p2) external view;
    function log(string memory p0, uint256 p1, address p2, uint256 p3) external view;
    function log(bool p0, bool p1, bool p2) external view;
    function log(address p0, bool p1, string memory p2, bool p3) external view;
    function log(address p0, string memory p1, bool p2, uint256 p3) external view;
    function log() external view;
    function log(bool p0, address p1, uint256 p2, string memory p3) external view;
    function log(bool p0, string memory p1, bool p2, address p3) external view;
    function log(bool p0, bool p1, uint256 p2, address p3) external view;
    function log(uint256 p0, uint256 p1, address p2, address p3) external view;
    function log(string memory p0, string memory p1, uint256 p2) external view;
    function log(string memory p0, uint256 p1, string memory p2) external view;
    function log(uint256 p0, uint256 p1, uint256 p2, string memory p3) external view;
    function log(string memory p0, address p1, uint256 p2, string memory p3) external view;
    function log(uint256 p0, address p1, uint256 p2) external view;
    function log(string memory p0, uint256 p1, string memory p2, string memory p3) external view;
    function log(uint256 p0, address p1, bool p2, uint256 p3) external view;
    function log(address p0, uint256 p1, string memory p2, address p3) external view;
    function log(uint256 p0, uint256 p1, address p2) external view;
    function log(string memory p0, string memory p1, address p2, bool p3) external view;
    function log(address p0, string memory p1, string memory p2, string memory p3) external view;
    function log(string memory p0, bool p1, address p2, uint256 p3) external view;
    function log(string memory p0, string memory p1, uint256 p2, string memory p3) external view;
    function log(uint256 p0, uint256 p1, string memory p2, uint256 p3) external view;
    function log(string memory p0, string memory p1, bool p2, string memory p3) external view;
    function log(string memory p0, uint256 p1, address p2, address p3) external view;
    function log(string memory p0, address p1, string memory p2, bool p3) external view;
    function log(address p0, string memory p1, bool p2, bool p3) external view;
    function log(uint256 p0, address p1, uint256 p2, bool p3) external view;
    function log(bool p0, address p1, uint256 p2) external view;
    function log(uint256 p0, string memory p1, address p2, address p3) external view;
    function log(bool p0, bool p1, uint256 p2, bool p3) external view;
    function log(address p0, string memory p1, uint256 p2, address p3) external view;
    function log(uint256 p0, address p1, string memory p2) external view;
    function log(string memory p0, address p1, uint256 p2, address p3) external view;
    function log(uint256 p0, string memory p1) external view;
    function log(string memory p0, bool p1, uint256 p2, uint256 p3) external view;
    function log(address p0, bool p1, address p2, address p3) external view;
    function log(address p0, address p1, address p2, address p3) external view;
    function log(address p0, uint256 p1, uint256 p2, bool p3) external view;
    function log(address p0, uint256 p1, bool p2) external view;
    function log(address p0, string memory p1, uint256 p2) external view;
    function log(uint256 p0, bool p1, string memory p2, string memory p3) external view;
    function log(uint256 p0, string memory p1, uint256 p2, bool p3) external view;
    function log(uint256 p0, address p1) external view;
    function log(uint256 p0, bool p1, bool p2, address p3) external view;
    function log(bool p0, uint256 p1, string memory p2, uint256 p3) external view;
    function log(bool p0, address p1, bool p2, bool p3) external view;
    function log(bool p0, string memory p1, uint256 p2, bool p3) external view;
    function log(uint256 p0, uint256 p1, address p2, string memory p3) external view;
    function log(bool p0, bool p1, string memory p2, string memory p3) external view;
    function log(string memory p0, string memory p1, string memory p2, address p3) external view;
    function log(bool p0, bool p1, bool p2, uint256 p3) external view;
    function log(bool p0, string memory p1, address p2, bool p3) external view;
    function log(address p0, address p1, string memory p2, bool p3) external view;
    function log(bool p0, address p1, string memory p2, address p3) external view;
    function log(string memory p0, bool p1, bool p2, address p3) external view;
    function log(uint256 p0, uint256 p1, string memory p2) external view;
    function log(uint256 p0, address p1, address p2, uint256 p3) external view;
    function log(string memory p0, bool p1, uint256 p2, string memory p3) external view;
    function log(uint256 p0, bool p1, bool p2, uint256 p3) external view;
    function log(address p0, string memory p1) external view;
    function log(address p0, bool p1) external view;
    function log(string memory p0, uint256 p1, uint256 p2, bool p3) external view;
    function log(string memory p0, address p1, bool p2, bool p3) external view;
    function log(uint256 p0, uint256 p1, string memory p2, bool p3) external view;
    function log(uint256 p0, string memory p1, address p2) external view;
    function log(address p0, uint256 p1, address p2) external view;
    function log(bool p0, string memory p1, string memory p2, uint256 p3) external view;
    function log(bool p0, address p1, uint256 p2, uint256 p3) external view;
    function log(string memory p0, uint256 p1, string memory p2, address p3) external view;
    function log(string memory p0, string memory p1, address p2, uint256 p3) external view;
    function log(string memory p0, uint256 p1, string memory p2, bool p3) external view;
    function log(bool p0, bool p1, uint256 p2, string memory p3) external view;
    function log(bool p0, uint256 p1, bool p2, uint256 p3) external view;
    function log(string memory p0, address p1, address p2, string memory p3) external view;
    function log(address p0, bool p1, string memory p2, uint256 p3) external view;
    function log(string memory p0, uint256 p1, address p2, bool p3) external view;
    function log(uint256 p0, string memory p1, uint256 p2, uint256 p3) external view;
    function log(address p0, uint256 p1) external view;
    function log(string memory p0, bool p1, bool p2) external view;
    function log(bool p0, address p1) external view;
    function log(string memory p0, uint256 p1, uint256 p2, string memory p3) external view;
    function log(uint256 p0, bool p1, string memory p2) external view;
    function log(address p0, uint256 p1, string memory p2, string memory p3) external view;
    function log(uint256 p0, bool p1, uint256 p2, address p3) external view;
    function log(uint256 p0, uint256 p1, address p2, uint256 p3) external view;
    function log(string memory p0, bool p1, bool p2, bool p3) external view;
    function log(string memory p0, bool p1, uint256 p2, bool p3) external view;
    function log(bool p0, bool p1, bool p2, address p3) external view;
    function log(address p0, bool p1, bool p2, uint256 p3) external view;
    function log(address p0, address p1, uint256 p2, address p3) external view;
    function log(string memory p0, bool p1, bool p2, uint256 p3) external view;
    function log(bool p0, uint256 p1, uint256 p2, string memory p3) external view;
    function log(string memory p0, string memory p1, string memory p2, uint256 p3) external view;
    function log(string memory p0, address p1, address p2, uint256 p3) external view;
    function log(address p0, address p1, string memory p2, address p3) external view;
    function log(bool p0, string memory p1) external view;
    function log(uint256 p0, string memory p1, address p2, bool p3) external view;
    function log(uint256 p0, address p1, bool p2, string memory p3) external view;
    function log(bool p0, uint256 p1, bool p2, string memory p3) external view;
    function log(uint256 p0, bool p1, uint256 p2, bool p3) external view;
    function log(string memory p0, address p1, string memory p2, uint256 p3) external view;
    function log(string memory p0, bool p1, address p2) external view;
    function log(string memory p0, bool p1, uint256 p2, address p3) external view;
    function log(address p0, address p1, address p2, uint256 p3) external view;
    function log(string memory p0, bool p1, address p2, bool p3) external view;
    function log(bool p0, string memory p1, address p2) external view;
    function log(string memory p0, string memory p1, address p2) external view;
    function log(bool p0, string memory p1, string memory p2, address p3) external view;
    function log(uint256 p0, uint256 p1, bool p2, address p3) external view;
    function log(bool p0, uint256 p1, bool p2, address p3) external view;
    function log(address p0, address p1, uint256 p2, bool p3) external view;
    function log(uint256 p0, address p1, bool p2) external view;
    function log(uint256 p0, string memory p1, address p2, string memory p3) external view;
    function log(address p0, bool p1, uint256 p2) external view;
    function log(uint256 p0, address p1, string memory p2, address p3) external view;
    function log(string memory p0, bool p1, bool p2, string memory p3) external view;
    function log(address p0, address p1, bool p2, address p3) external view;
    function log(string memory p0, uint256 p1, address p2, string memory p3) external view;
    function log(address p0, string memory p1, string memory p2, address p3) external view;
    function log(bool p0, bool p1, address p2, string memory p3) external view;
    function log(address p0, uint256 p1, address p2, bool p3) external view;
    function log(uint256 p0, bool p1, address p2, address p3) external view;
    function log(address p0, uint256 p1, string memory p2) external view;
    function log(address p0, uint256 p1, bool p2, address p3) external view;
    function log(uint256 p0, uint256 p1, bool p2, string memory p3) external view;
    function log(bool p0, string memory p1, address p2, uint256 p3) external view;
    function log(address p0, bool p1, address p2, bool p3) external view;
    function log(bool p0, address p1, string memory p2, string memory p3) external view;
    function log(address p0, bool p1, address p2, uint256 p3) external view;
    function log(string memory p0, uint256 p1, uint256 p2, uint256 p3) external view;
    function log(string memory p0, bool p1, string memory p2, string memory p3) external view;
    function log(address p0, address p1, bool p2, string memory p3) external view;
    function log(string memory p0, address p1, string memory p2, address p3) external view;
    function log(uint256 p0, uint256 p1, bool p2, bool p3) external view;
    function log(string memory p0, uint256 p1, bool p2, string memory p3) external view;
    function log(uint256 p0, bool p1, address p2, string memory p3) external view;
    function log(uint256 p0, string memory p1, bool p2, address p3) external view;
    function log(uint256 p0, string memory p1, string memory p2, uint256 p3) external view;
    function log(bool p0, string memory p1, string memory p2) external view;
    function log(string memory p0, string memory p1, bool p2) external view;
    function log(uint256 p0, string memory p1, string memory p2) external view;
    function log(uint256 p0, string memory p1, string memory p2, bool p3) external view;
    function log(bool p0, uint256 p1, address p2, bool p3) external view;
    function log(string memory p0, address p1, address p2, bool p3) external view;
    function log(string memory p0, uint256 p1) external view;
    function log(address p0, uint256 p1, uint256 p2) external view;
    function log(uint256 p0, bool p1, bool p2, bool p3) external view;
    function log(uint256 p0, string memory p1, uint256 p2, string memory p3) external view;
    function log(bool p0, bool p1, string memory p2, bool p3) external view;
    function log(uint256 p0, string memory p1, bool p2, bool p3) external view;
    function log(address p0, string memory p1, bool p2, string memory p3) external view;
    function log(uint256 p0, address p1, address p2) external view;
    function log(address p0, address p1, uint256 p2, uint256 p3) external view;
    function log(bool p0, uint256 p1, uint256 p2, bool p3) external view;
    function log(address p0, uint256 p1, string memory p2, uint256 p3) external view;
    function log(bool p0, bool p1, address p2, bool p3) external view;
    function log(bool p0, address p1, string memory p2, uint256 p3) external view;
    function log(string memory p0, string memory p1, bool p2, address p3) external view;
    function log(string memory p0, string memory p1, uint256 p2, bool p3) external view;
    function log(string memory p0, bool p1) external view;
    function log(bool p0, uint256 p1, string memory p2) external view;
    function log(address p0, bool p1, uint256 p2, bool p3) external view;
    function log(uint256 p0, uint256 p1, uint256 p2, bool p3) external view;
    function log(address p0, uint256 p1, bool p2, string memory p3) external view;
    function log(string memory p0, uint256 p1, string memory p2, uint256 p3) external view;
    function log(uint256 p0, bool p1, uint256 p2, uint256 p3) external view;
    function log(string memory p0, address p1, bool p2) external view;
    function log(string memory p0, bool p1, uint256 p2) external view;
    function log(string memory p0, uint256 p1, uint256 p2) external view;
    function log(string memory p0, uint256 p1, bool p2) external view;
    function log(address p0, bool p1, bool p2, bool p3) external view;
    function log(uint256 p0, address p1, string memory p2, bool p3) external view;
    function log(address p0, bool p1, uint256 p2, address p3) external view;
    function log(bool p0, uint256 p1, bool p2, bool p3) external view;
    function log(uint256 p0, string memory p1, bool p2, uint256 p3) external view;
    function log(address p0, string memory p1, bool p2) external view;
    function log(address p0, uint256 p1, string memory p2, bool p3) external view;
    function log(address p0, bool p1, bool p2, address p3) external view;
    function log(uint256 p0, uint256 p1, uint256 p2) external view;
    function log(bool p0, address p1, address p2) external view;
    function log(uint256 p0, string memory p1, bool p2, string memory p3) external view;
    function log(uint256 p0, string memory p1, string memory p2, address p3) external view;
    function log(bool p0, address p1, uint256 p2, bool p3) external view;
    function log(string memory p0, string memory p1, bool p2, uint256 p3) external view;
    function log(bool p0, address p1, address p2, string memory p3) external view;
    function log(address p0, address p1) external view;
    function log(bool p0, string memory p1, bool p2) external view;
    function log(bool p0, string memory p1, bool p2, bool p3) external view;
    function log(uint256 p0, address p1, uint256 p2, string memory p3) external view;
    function log(uint256 p0, bool p1, bool p2, string memory p3) external view;
    function log(uint256 p0, bool p1, uint256 p2, string memory p3) external view;
    function log(string memory p0, string memory p1, string memory p2, string memory p3) external view;
    function log(bool p0, address p1, string memory p2) external view;
    function log(address p0, bool p1, bool p2, string memory p3) external view;
    function log(string memory p0, bool p1, string memory p2, address p3) external view;
    function log(string memory p0, uint256 p1, bool p2, address p3) external view;
    function log(string memory p0, address p1, string memory p2) external view;
    function log(string memory p0, uint256 p1, uint256 p2, address p3) external view;
    function log(string memory p0, bool p1, string memory p2) external view;
    function log(bool p0, address p1, string memory p2, bool p3) external view;
    function log(uint256 p0, address p1, bool p2, bool p3) external view;
    function log(bool p0, bool p1, string memory p2, uint256 p3) external view;
    function log(string memory p0, uint256 p1, bool p2, uint256 p3) external view;
    function log(bool p0, uint256 p1, string memory p2, bool p3) external view;
    function log(uint256 p0, string memory p1, address p2, uint256 p3) external view;
    function log(bool p0, uint256 p1, bool p2) external view;
    function log(string memory p0, string memory p1, address p2, string memory p3) external view;
    function log(uint256 p0, uint256 p1, bool p2, uint256 p3) external view;
    function log(address p0, bool p1, bool p2) external view;
    function log(uint256 p0, bool p1, string memory p2, bool p3) external view;
    function log(string memory p0, address p1, address p2, address p3) external view;
    function log(address p0, address p1, string memory p2, uint256 p3) external view;
    function log(uint256 p0, bool p1, string memory p2, address p3) external view;
    function log(uint256 p0, address p1, bool p2, address p3) external view;
    function log(address p0, string memory p1, address p2) external view;
    function log(address p0, bool p1, address p2) external view;
    function log(address p0, address p1, bool p2) external view;
    function log(string memory p0, string memory p1, uint256 p2, uint256 p3) external view;
    function log(bool p0, bool p1, address p2, address p3) external view;
    function log(bool p0, uint256 p1, string memory p2, string memory p3) external view;
    function log(uint256 p0, uint256 p1) external view;
    function log(address p0, string memory p1, address p2, string memory p3) external view;
    function log(address p0, address p1, address p2, string memory p3) external view;
    function log(uint256 p0) external view;
    function log(string memory p0, address p1, uint256 p2, uint256 p3) external view;
    function log(bool p0, bool p1, string memory p2, address p3) external view;
    function log(uint256 p0, uint256 p1, uint256 p2, address p3) external view;
    function log(address p0, string memory p1, string memory p2) external view;
    function log(string memory p0, address p1, uint256 p2, bool p3) external view;
    function log(string memory p0, address p1, address p2) external view;
    function log(address p0, address p1, uint256 p2, string memory p3) external view;
    function log(bool p0, uint256 p1, string memory p2, address p3) external view;
    function logAddress(address p0) external view;
    function logBool(bool p0) external view;
    function logBytes(bytes memory p0) external view;
    function logBytes1(bytes1 p0) external view;
    function logBytes10(bytes10 p0) external view;
    function logBytes11(bytes11 p0) external view;
    function logBytes12(bytes12 p0) external view;
    function logBytes13(bytes13 p0) external view;
    function logBytes14(bytes14 p0) external view;
    function logBytes15(bytes15 p0) external view;
    function logBytes16(bytes16 p0) external view;
    function logBytes17(bytes17 p0) external view;
    function logBytes18(bytes18 p0) external view;
    function logBytes19(bytes19 p0) external view;
    function logBytes2(bytes2 p0) external view;
    function logBytes20(bytes20 p0) external view;
    function logBytes21(bytes21 p0) external view;
    function logBytes22(bytes22 p0) external view;
    function logBytes23(bytes23 p0) external view;
    function logBytes24(bytes24 p0) external view;
    function logBytes25(bytes25 p0) external view;
    function logBytes26(bytes26 p0) external view;
    function logBytes27(bytes27 p0) external view;
    function logBytes28(bytes28 p0) external view;
    function logBytes29(bytes29 p0) external view;
    function logBytes3(bytes3 p0) external view;
    function logBytes30(bytes30 p0) external view;
    function logBytes31(bytes31 p0) external view;
    function logBytes32(bytes32 p0) external view;
    function logBytes4(bytes4 p0) external view;
    function logBytes5(bytes5 p0) external view;
    function logBytes6(bytes6 p0) external view;
    function logBytes7(bytes7 p0) external view;
    function logBytes8(bytes8 p0) external view;
    function logBytes9(bytes9 p0) external view;
    function logInt(int256 p0) external view;
    function logString(string memory p0) external view;
    function logUint(uint256 p0) external view;
}