name: Docs

on:
  push:
    branches: [main]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-22.04
    permissions:
      contents: write
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - uses: actions/checkout@v4

      - name: Setup mdBook
        uses: peaceiris/actions-mdbook@v1
        with:
          mdbook-version: "latest"

      - name: Setup rust toolchain
        uses: dtolnay/rust-toolchain@nightly

      - name: Build rust docs
        run: |
          RUSTDOCFLAGS="--enable-index-page -Zunstable-options" cargo doc \
          --workspace \
          --no-deps \
          --document-private-items

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./target/doc
